"""Aggregate per-run output CSVs into LaTeX table fragments for the dissertation.

Reads the reproducible artifacts under output/ and emits booktabs-style
``.tex`` fragments (each a standalone ``tabular`` for \\input{}). Keeps the
dissertation tables reproducible — no manual copy-paste.

Run (after the pipeline / attack / dynamics runs have produced output/):
    python3 -m src.reporting.aggregate_tables

Emits to output/tables/:
    table_data_quality.tex   — dataset + data-quality breakdown
    table_rq1_attacks.tex    — Attack Δ per attack × model (real vs synthetic)
    table_rq3_correlation.tex— atypicality–Δ correlation + group contrast
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

OUTPUT = Path("output")
DEFAULT_OUT = OUTPUT / "tables"

MODEL_ORDER = [
    "baseline", "webpa", "peerrank-impute", "peerrank-exclude",
    "peerhits-impute", "peerhits-exclude",
]
ATTACK_ORDER = [
    "uniform-inflation", "targeted-downvote",
    "zero-self-full", "zero-self-partial", "single-outlier",
]


def _tex(s: str) -> str:
    """Escape LaTeX-special characters in a label."""
    return (str(s).replace("\\", r"\textbackslash{}")
            .replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")
            .replace("#", r"\#"))


def _wrap(caption: str, label: str, colspec: str, header: str,
          body_rows: list[str]) -> str:
    lines = [
        "% Auto-generated by src.reporting.aggregate_tables — do not edit by hand.",
        r"\begin{table}[t]", r"  \centering",
        f"  \\caption{{{caption}}}", f"  \\label{{{label}}}",
        f"  \\begin{{tabular}}{{{colspec}}}", r"    \toprule",
        f"    {header} \\\\", r"    \midrule",
    ]
    for r in body_rows:
        # Bare table commands (e.g. \addlinespace) take no row terminator.
        lines.append(f"    {r}" if r.startswith("\\") else f"    {r} \\\\")
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def data_quality_table(out: Path) -> Path:
    dq = json.loads((OUTPUT / "data_quality_report.json").read_text())
    cls = pd.read_csv(OUTPUT / "dynamics" / "classifications.csv")

    n = len(cls)
    degen = cls["degenerate"].sum()
    clean = n - degen
    causes = cls.loc[cls["degenerate"], "degenerate_cause"].value_counts()

    rows = [
        f"CSV sessions & {dq['csv_count']}",
        f"Score matrices & {dq['total_matrices']}",
        f"Unique teams & {dq['unique_teams']}",
        f"Clean matrices & {int(clean)}",
        f"Degenerate matrices & {int(degen)}",
        f"\\quad non-submitter & {int(causes.get('non_submitter', 0))}",
        f"\\quad flat & {int(causes.get('flat', 0))}",
        f"\\quad both & {int(causes.get('both', 0))}",
        f"Teams excluded ($\\geq$50\\% missing) & {dq['teams_excluded']}",
        f"Non-submitting rater events & {dq['missing_raters']}",
        f"Model runs (succeeded / failed) & {dq['succeeded']} / {dq['failed']}",
    ]
    tex = _wrap(
        "Dataset and data-quality breakdown across all sessions.",
        "tab:data-quality", "lr", "Metric & Value", rows,
    )
    path = out / "table_data_quality.tex"
    path.write_text(tex)
    return path


def rq1_attacks_table(out: Path) -> Path:
    df = pd.read_csv(OUTPUT / "attacks" / "attack_summary.csv")
    piv = df.pivot_table(index=["attack", "model"], columns="source",
                         values="mean_delta")

    header = "Attack & Model & Real $\\Delta$ & Synthetic $\\Delta$"
    rows: list[str] = []
    for atk in ATTACK_ORDER:
        if atk not in piv.index.get_level_values("attack"):
            continue
        for i, mdl in enumerate(MODEL_ORDER):
            if (atk, mdl) not in piv.index:
                continue
            r = piv.loc[(atk, mdl)]
            real = f"{r.get('real', float('nan')):.3f}" if "real" in r and pd.notna(r.get("real")) else "--"
            syn = f"{r.get('synthetic', float('nan')):.3f}" if "synthetic" in r and pd.notna(r.get("synthetic")) else "--"
            atk_cell = _tex(atk) if i == 0 else ""
            rows.append(f"{atk_cell} & {_tex(mdl)} & {real} & {syn}")
        rows.append(r"\addlinespace")
    if rows and rows[-1] == r"\addlinespace":
        rows.pop()

    tex = _wrap(
        "Mean Attack $\\Delta$ per attack $\\times$ model on real clean "
        "matrices ($n{=}217$) versus the synthetic cohort. Lower is more "
        "robust; $\\Delta{=}0$ denotes full immunity.",
        "tab:rq1-attacks", "llrr", header, rows,
    )
    path = out / "table_rq1_attacks.tex"
    path.write_text(tex)
    return path


def rq3_correlation_table(out: Path) -> Path:
    corr = pd.read_csv(OUTPUT / "dynamics" / "atypicality_summary.csv")
    contrast = pd.read_csv(OUTPUT / "dynamics" / "atypicality_group_contrast.csv")

    header = ("Subset & $n$ & Pearson $r$ & $p$ & "
              "Anom.\\ mean$\\Delta$ & Typ.\\ mean$\\Delta$ & MW $p$")
    rows = []
    for _, c in corr.iterrows():
        sub = c["subset"]
        g = contrast.loc[contrast["subset"] == sub]
        if len(g):
            g = g.iloc[0]
            anom = f"{g['delta_mean_anomalous']:.3f}"
            typ = f"{g['delta_mean_typical']:.3f}"
            mwp = f"{g['mannwhitney_p']:.1e}"
        else:
            anom = typ = mwp = "--"
        rows.append(
            f"{_tex(sub)} & {int(c['n'])} & {c['pearson_r']:+.3f} & "
            f"{c['p_value']:.1e} & {anom} & {typ} & {mwp}"
        )
    tex = _wrap(
        "RQ3: Pearson correlation between team atypicality (Mahalanobis "
        "$d^2$) and cross-model IWF $\\Delta$, with the Anomalous-vs-Typical "
        "$\\Delta$ group contrast (Mann--Whitney $p$).",
        "tab:rq3-correlation", "lrrrrrr", header, rows,
    )
    path = out / "table_rq3_correlation.tex"
    path.write_text(tex)
    return path


def main() -> None:
    ap = argparse.ArgumentParser(prog="python3 -m src.reporting.aggregate_tables")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help=f"Output directory (default: {DEFAULT_OUT})")
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    for fn in (data_quality_table, rq1_attacks_table, rq3_correlation_table):
        path = fn(args.out)
        print(f"  Wrote {path}")


if __name__ == "__main__":
    main()
